import { FileSpreadsheet } from 'lucide-react';
import './PreviewTable.css'; // We'll create this for custom styling

interface PreviewTableProps {
    data: string; // Now accepts HTML string
}

export function PreviewTable({ data }: PreviewTableProps) {
    if (!data) {
        return (
            <div className="text-center py-12 bg-slate-50 rounded-lg border border-slate-200">
                <FileSpreadsheet className="w-12 h-12 text-slate-300 mx-auto mb-3" />
                <p className="text-slate-500">No data found in this sheet</p>
            </div>
        );
    }

    return (
        <div className="overflow-hidden rounded-lg border border-slate-200 shadow-sm bg-white p-4">
            {/* Render the HTML table generated by sheet_to_html */}
            <div
                className="excel-preview-container max-h-[70vh] overflow-auto custom-scrollbar"
                dangerouslySetInnerHTML={{ __html: data }}
            />
        </div>
    );
}
